import type { IconType } from 'react-icons';
import {
  SiTypescript,
  SiReact,
  SiTailwindcss,
  SiReactquery,
  SiNginx,
  SiPython,
  SiFastapi,
  SiCelery,
  SiPydantic,
  SiPostgresql,
  SiGitlab,
  SiGithubactions,
  SiDocker,
  SiKubernetes,
  SiGrafana,
  SiGit,
  SiRailway,
  SiRender,
  SiPytorch,
  SiTensorflow,
  SiKeras,
  SiScikitlearn,
  SiNumpy,
  SiPandas,
  SiHuggingface,
  SiLangchain,
  SiN8N,
} from 'react-icons/si';
import { FaAws } from 'react-icons/fa';

// Explicit registry so the bundle only ships the glyphs we actually render
// (importing the full react-icons set balloons the bundle by megabytes).
export const iconRegistry: Record<string, IconType> = {
  SiTypescript,
  SiReact,
  SiTailwindcss,
  SiReactquery,
  SiNginx,
  SiPython,
  SiFastapi,
  SiCelery,
  SiPydantic,
  SiPostgresql,
  SiGitlab,
  SiGithubactions,
  SiDocker,
  SiKubernetes,
  SiGrafana,
  SiGit,
  SiRailway,
  SiRender,
  SiPytorch,
  SiTensorflow,
  SiKeras,
  SiScikitlearn,
  SiNumpy,
  SiPandas,
  SiHuggingface,
  SiLangchain,
  SiN8N,
  FaAws,
};
